include:
  - board: nice_nano_v2
    shield: corne_left
  - board: nice_nano_v2
    shield: corne_right
  - board: nice_nano_v2
    shield: settings_reset

    # Add custom dongle and a peripheral left corne
  - board: nice_nano_v2
    shield: corne_dongle
  - board: nice_nano_v2
    shield: corne_peripheral_left
